### ISSUE TITLE
[MID]: Saugoti apartamentų kambarius

### ISSUE THREAD

**Issue by joklek** [uzspringom-javainiais/tripper-is#18]
Pagal užsakovo atsakymą, visi jų kambariai lokacijoje yra vienviečiai ir yra turi savo numerį. Tai reiktų tai įgyvendinti. Arba kaip Apartmentų bundle kažkaip, ar pnš.

**Comment by joklek** [comment]
https://github.com/uzspringom-javainiais/tripper-is/pull/47

**Comment by taskiukas** [comment]
done
