### ISSUE TITLE
[LOW] Atnaujinti projekto Postman metodus

### ISSUE THREAD

**Issue by pauliuskalv** [uzspringom-javainiais/tripper-is#29]

**Comment by taskiukas** [comment]
mano nuomone postmanas tik laiko gaisimas ir jokios praktines naudos nenesa dabar. tik valgo laika. koncentruokimes kitur.

**Comment by joklek** [comment]
Su postmanu gali parankiai pasitestinti querius, man asmeniškai tai zjbs,
bet pritariu rokui, kad per daug stengtis nevertėtų
