### ISSUE TITLE
Create edit employee endpoint

### ISSUE THREAD

**Issue by Adomas202** [uzspringom-javainiais/tripper-is#35]
Turi buti toks: api/account/${employee.id}.

Jeigu pakeiciu tik viena darbuotojo fielda, tai paupdatinti reikia tik ta ir kitu neliesti.
Speju reikia padaryti, kad nera galima keisti darbuotojo slaptazodzio.
Jeigu roliu masyvas ateina tuscias, tada reikia palikti tas, kurios pries tai buvo.

**Comment by joklek** [comment]
https://github.com/uzspringom-javainiais/tripper-is/pull/36

`POST /api/account/{id}` sumergina tavo atsiųstus pakitusius laukus į db (neveikia, jei atsiųsi lauką kaip null arba empty masyvą, nes ignoruoja tuščias reikšmes. Biški bullshit, bet ant greičio nesugalvojau kaip kitaip lengvai padaryti)
`PUT /api/account/{id}` tiesiog įdeda ką gavo į db (patikrina aišku ar validu)
`GET /api/me/trips` gauna savo organizuojamas keliones

**Comment by taskiukas** [comment]
@Adomas202 ar veikia?

**Comment by Adomas202** [comment]
@joklek Tai PUT sukuria naują employee, o POST paeditina?
Jeigu as sukuriu kelione, tai ja turetu rodyti prie ```api/me/trips```? Nes dabar nerodo :(

**Comment by joklek** [comment]
Aš debiliškai buvau padaręs ir pataisiau. Dabar PATCH paeditina, o PUT uždeda ant accounto tą ką atsiunti.

pvz 
`PUT /api/account/{id}` tiesiog įdeda ką gavo į db (patikrina aišku ar validu)
`PATCH /api/account/{id}` uždeda ką gavo kaip delta, pakitimą
`POST /api/account` sukuria naują acc su nauju id

**Comment by Adomas202** [comment]
Panasu, kad viskas good dabar
